### ISSUE TITLE
score estimate doesn't recognize dead groups as well as java client

### ISSUE THREAD

**Issue by kpfleger** [IlyaKirillov/GoUniverse#55]
At the end of a game, the score estimator doesn't seem to do a good job at all, not recognizing obviously dead groups as dead. The behavior is different than the normal Java KGS client, which surprises me since I would have expected this to be a server side computation.

**Comment by IlyaKirillov** [comment]
It's not the same as in the regular client. You have to mark dead groups by your own in the score estimate window.
This option (i mean SE) doesn't come from server, it's client-side feature, that's why i had decided to let users mark dead stones by their own instead of implementing an algorithm to determine of dead groups (it's rly hard problem). 

In fact, i like my own realization of SE much better than how it works in the regular client, because it will be working without any issues (like situations when SE couldn't estimate) and also because the user can mark dead stones much preciclsly than any algorithm.
